# Site settings
title: joelgaff.com
email: joel@joelgaff.com
description: >-
  Joel Gaff, Jr. is a software developer based in Portland, Oregon, USA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joelgaff.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: joelgaff

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalink structure (custom to preserve Google rankings)
permalink: /blog/:title/
